// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ActiveUserAvatar: typeof import('./components/ActiveUserAvatar.vue')['default']
    Banner: typeof import('./components/Banner.vue')['default']
    Controls: typeof import('./components/NewForm/Controls.vue')['default']
    DefaultAvatar: typeof import('./components/DefaultAvatar.vue')['default']
    DevJson: typeof import('./components/DevJson.vue')['default']
    FloatingDelete: typeof import('./components/FloatingDelete.vue')['default']
    LastUpdated: typeof import('./components/LastUpdated.vue')['default']
    NewProfileForm: typeof import('./components/NewProfileForm.vue')['default']
    ProfileForm: typeof import('./components/ProfileForm.vue')['default']
    ProfileMenu: typeof import('./components/ProfileMenu.vue')['default']
    README: typeof import('./components/README.md')['default']
    RewardCard: typeof import('./components/RewardCard.vue')['default']
    RewardClaimedList: typeof import('./components/RewardClaimedList.vue')['default']
    RewardForm: typeof import('./components/RewardForm.vue')['default']
    RewardProgress: typeof import('./components/RewardProgress.vue')['default']
    RewardWishList: typeof import('./components/RewardWishList.vue')['default']
  }
}

export { }
